# Generated by Django 3.2.13 on 2022-06-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('edad', models.CharField(max_length=2)),
                ('dui', models.CharField(max_length=9, unique=True)),
                ('estatura', models.DecimalField(decimal_places=2, max_digits=6)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=4)),
                ('enfermedades', models.TextField()),
                ('afecciones', models.TextField()),
            ],
        ),
    ]
