# Generated by Django 3.2.13 on 2022-06-21 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0004_auto_20220621_0149'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Municipio',
            new_name='City',
        ),
        migrations.RenameModel(
            old_name='Departamento',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='departamento',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='municipio',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='departamento',
            new_name='country',
        ),
    ]
