# Generated by Django 3.2.13 on 2022-06-21 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0006_auto_20220621_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAlimenticio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=25)),
                ('tiempo', models.CharField(max_length=2)),
                ('descripcion', models.TextField()),
                ('cantCarbohidratos', models.IntegerField(max_length=2)),
                ('cantProteina', models.IntegerField(max_length=2)),
                ('cantGrasas', models.IntegerField(max_length=2)),
                ('cantVitaminas', models.IntegerField(max_length=2)),
                ('cantMinerales', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Paciente.planalimenticio'),
        ),
    ]
