# Generated by Django 3.2.13 on 2022-06-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0008_auto_20220622_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
