# Generated by Django 3.2.13 on 2022-06-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0013_alter_planalimenticio_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.EmailField(default='Some String', max_length=255),
        ),
    ]
