# Generated by Django 3.2.13 on 2022-06-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0014_paciente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
