# Generated by Django 3.2.13 on 2022-06-26 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0015_alter_paciente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Paciente.departamento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Paciente.municipio'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Paciente.planalimenticio'),
        ),
    ]
