# Generated by Django 3.2.13 on 2022-06-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0016_auto_20220626_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dui',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
