# Generated by Django 3.2.13 on 2022-06-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0018_alter_paciente_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dui',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
