# Generated by Django 3.2.13 on 2022-06-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0019_alter_paciente_dui'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
