# Generated by Django 3.2.13 on 2022-06-27 03:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0022_auto_20220627_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dui',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Cantidad de digitos insuficientes o ingreso alguna letra', regex='^\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(code='nomatch', message='Cantidad de digitos insuficientes o ingreso alguna letra', regex='^\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estatura',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(code='nomatch', message='Cantidad de digitos insuficientes o ingreso alguna letra', regex='^\\d{5}$')]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.RegexValidator(code='nomatch', message='Cantidad de digitos insuficientes o ingreso alguna letra', regex='^\\d{5}$')]),
        ),
    ]
