# Generated by Django 3.2.13 on 2022-06-27 03:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0023_auto_20220627_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='estatura',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.RegexValidator(code='nomatch', message='Cantidad de digitos insuficientes o ingreso alguna letra', regex='^\\d{5}$')]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
