# Generated by Django 3.2.13 on 2022-06-27 03:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0024_auto_20220627_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='estatura',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(code='nomatch', message='Cantidad de digitos insuficientes o ingreso alguna letra', regex='^\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='peso',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(code='nomatch', message='Cantidad de digitos insuficientes o ingreso alguna letra', regex='^\\d+\\.\\d{2}$')]),
        ),
    ]
