# Generated by Django 3.2.13 on 2022-06-15 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MUsuario',
            new_name='RUsuario',
        ),
    ]
