# Generated by Django 3.2.13 on 2022-06-15 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_auto_20220615_2112'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GestionarUsuario',
            new_name='Usuario',
        ),
    ]
