# Generated by Django 3.2.13 on 2022-06-16 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0005_auto_20220616_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='update',
            new_name='updated',
        ),
    ]
