# Generated by Django 3.2.13 on 2022-06-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0006_rename_update_usuario_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(max_length=50, verbose_name='Rol'),
        ),
    ]
