# Generated by Django 3.2.13 on 2022-06-19 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0007_alter_usuario_rol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
